
package introsde.spotifylayer.soap.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SpotiImplService", targetNamespace = "http://ws.soap.spotifylayer.introsde/", wsdlLocation = "https://sdeproject-spotilayer.herokuapp.com/spoti?wsdl")
public class SpotiImplService
    extends Service
{

    private final static URL SPOTIIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SPOTIIMPLSERVICE_EXCEPTION;
    private final static QName SPOTIIMPLSERVICE_QNAME = new QName("http://ws.soap.spotifylayer.introsde/", "SpotiImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sdeproject-spotilayer.herokuapp.com/spoti?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPOTIIMPLSERVICE_WSDL_LOCATION = url;
        SPOTIIMPLSERVICE_EXCEPTION = e;
    }

    public SpotiImplService() {
        super(__getWsdlLocation(), SPOTIIMPLSERVICE_QNAME);
    }

    public SpotiImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPOTIIMPLSERVICE_QNAME, features);
    }

    public SpotiImplService(URL wsdlLocation) {
        super(wsdlLocation, SPOTIIMPLSERVICE_QNAME);
    }

    public SpotiImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPOTIIMPLSERVICE_QNAME, features);
    }

    public SpotiImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpotiImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Spoti
     */
    @WebEndpoint(name = "SpotiImplPort")
    public Spoti getSpotiImplPort() {
        return super.getPort(new QName("http://ws.soap.spotifylayer.introsde/", "SpotiImplPort"), Spoti.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Spoti
     */
    @WebEndpoint(name = "SpotiImplPort")
    public Spoti getSpotiImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soap.spotifylayer.introsde/", "SpotiImplPort"), Spoti.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPOTIIMPLSERVICE_EXCEPTION!= null) {
            throw SPOTIIMPLSERVICE_EXCEPTION;
        }
        return SPOTIIMPLSERVICE_WSDL_LOCATION;
    }

}
